// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $SimplePromptInlineButtom from "./islands/SimplePromptInlineButtom.tsx";
import * as $SimplePromptTextButton from "./islands/SimplePromptTextButton.tsx";
import * as $SimplePromptURLButton from "./islands/SimplePromptURLButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/SimplePromptInlineButtom.tsx": $SimplePromptInlineButtom,
    "./islands/SimplePromptTextButton.tsx": $SimplePromptTextButton,
    "./islands/SimplePromptURLButton.tsx": $SimplePromptURLButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
